"""bool

Revision ID: 207e11194557
Revises: d679bad6c0b6
Create Date: 2025-06-02 16:34:38.229426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207e11194557'
down_revision: Union[str, None] = 'd679bad6c0b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('password_protected', sa.Boolean(), nullable=False, server_default='f'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paste', 'password_protected')
    # ### end Alembic commands ###
