"""test

Revision ID: bc6a52371ac2
Revises: 
Create Date: 2025-05-16 17:38:08.631849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6a52371ac2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paste',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paste', sa.LargeBinary(), nullable=False),
    sa.Column('iv', sa.LargeBinary(), nullable=False),
    sa.Column('signature', sa.LargeBinary(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('opens_limit', sa.Integer(), nullable=True),
    sa.Column('current_opens', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paste_id'), 'paste', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paste_id'), table_name='paste')
    op.drop_table('paste')
    # ### end Alembic commands ###
