"""missing field

Revision ID: d679bad6c0b6
Revises: bc6a52371ac2
Create Date: 2025-06-02 16:29:52.844374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd679bad6c0b6'
down_revision: Union[str, None] = 'bc6a52371ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paste', 'current_opens',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paste', 'current_opens',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
